from routers.students import students_router
from routers.parents import parents_router
from routers.studentDetails import student_detail_router
from routers.faculties import faculty_router
from routers.welayatlar import welayat_router
from routers.parentStatus import parent_status_router
from routers.authentication import authentication_router
from routers.details import detail_router
from routers.thirddetails import thirddetails_router
from routers.ids_router import ids_router