from models.models import Students
from models.models import Parents
from models.models import studentDetails
from models.models import Faculties
from models.models import Welayatlar
from models.models import parentStatus
from models.schemas import add_student
from models.schemas import add_parent
from models.schemas import add_studentDetail
from models.schemas import update_parent
from models.schemas import update_student